# IPO Success Prediction – Phase 1

## Notebook 01: Build Master IPO Table

**Objective**
- Load official NSE IPO issue data (2010–2024)
- Inspect and validate columns
- Create a clean, time-sorted master IPO table
- No modeling in this notebook

**Data Source**
- NSE IPO Past Issues dataset (2010–2024)

**Research Note**
This notebook strictly focuses on data ingestion and preparation.

In [2]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
DATA_RAW = PROJECT_ROOT / "data" / "raw"

PROJECT_ROOT, DATA_RAW

(PosixPath('/Users/jeeveshmishra/Desktop/IPO-Success-Prediction/IPO-Success-Prediction'),
 PosixPath('/Users/jeeveshmishra/Desktop/IPO-Success-Prediction/IPO-Success-Prediction/data/raw'))

In [3]:
ipo_master = pd.read_csv(
    DATA_RAW / "IPO-PastIssue-01-01-2010-to-31-12-2024.csv"
)

ipo_master["DATE OF LISTING"] = pd.to_datetime(
    ipo_master["DATE OF LISTING"], errors="coerce", dayfirst=True
)

ipo_master.head()

/var/folders/fk/0kqynd_95d71j1htw9b057j00000gn/T/ipykernel_65107/3449285669.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ipo_master["DATE OF LISTING"] = pd.to_datetime(

,COMPANY NAME,SECURITY TYPE,ISSUE PRICE,Symbol,ISSUE START DATE,ISSUE END DATE,PRICE RANGE,DATE OF LISTING
0,Indo Farm Equipment Limited,EQ,215,INDOFARM,31-DEC-2024,02-JAN-2025,Rs.204 to Rs.215,2025-01-07
1,Anya Polytech & Fertilizers Limited,SME,14,ANYA,26-DEC-2024,30-DEC-2024,Rs.13 to Rs.14,2025-01-02
2,Unimech Aerospace and Manufacturing Limited,EQ,785,UNIMECH,23-DEC-2024,26-DEC-2024,Rs.745 to Rs.785,2024-12-31
3,Carraro India Limited,EQ,704,CARRARO,20-DEC-2024,24-DEC-2024,Rs.668 to Rs.704,2024-12-30
4,Senores Pharmaceuticals Limited,EQ,391,SENORES,20-DEC-2024,24-DEC-2024,Rs.372 to Rs.391,2024-12-30

In [4]:
ipo_eq = ipo_master[
    ipo_master["SECURITY TYPE"] == "EQ"
].copy()

ipo_eq = ipo_eq.dropna(subset=["DATE OF LISTING", "Symbol"])

ipo_eq["listing_year"] = ipo_eq["DATE OF LISTING"].dt.year
ipo_eq["listing_month"] = ipo_eq["DATE OF LISTING"].dt.month

ipo_eq.head()

,COMPANY NAME,SECURITY TYPE,ISSUE PRICE,Symbol,ISSUE START DATE,ISSUE END DATE,PRICE RANGE,DATE OF LISTING,listing_year,listing_month
0,Indo Farm Equipment Limited,EQ,215,INDOFARM,31-DEC-2024,02-JAN-2025,Rs.204 to Rs.215,2025-01-07,2025,1
2,Unimech Aerospace and Manufacturing Limited,EQ,785,UNIMECH,23-DEC-2024,26-DEC-2024,Rs.745 to Rs.785,2024-12-31,2024,12
3,Carraro India Limited,EQ,704,CARRARO,20-DEC-2024,24-DEC-2024,Rs.668 to Rs.704,2024-12-30,2024,12
4,Senores Pharmaceuticals Limited,EQ,391,SENORES,20-DEC-2024,24-DEC-2024,Rs.372 to Rs.391,2024-12-30,2024,12
5,Ventive Hospitality Limited,EQ,643,VENTIVE,20-DEC-2024,24-DEC-2024,Rs.610 to Rs.643,2024-12-30,2024,12

In [5]:
out_path = DATA_RAW / "ipo_master_eq.csv"
ipo_eq.to_csv(out_path, index=False)

out_path

PosixPath('/Users/jeeveshmishra/Desktop/IPO-Success-Prediction/IPO-Success-Prediction/data/raw/ipo_master_eq.csv')